# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cooccurrence.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'cooccurrence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ooccurrence.proto\x12\tbringyour\"&\n\x08InnerMap\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x04\"?\n\x08OuterMap\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12&\n\tinner_map\x18\x02 \x03(\x0b\x32\x13.bringyour.InnerMap\"3\n\tOuterMaps\x12&\n\touter_map\x18\x01 \x03(\x0b\x32\x13.bringyour.OuterMapB\x18Z\x16\x62ringyour.com/protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cooccurrence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026bringyour.com/protocol'
  _globals['_INNERMAP']._serialized_start=33
  _globals['_INNERMAP']._serialized_end=71
  _globals['_OUTERMAP']._serialized_start=73
  _globals['_OUTERMAP']._serialized_end=136
  _globals['_OUTERMAPS']._serialized_start=138
  _globals['_OUTERMAPS']._serialized_end=189
# @@protoc_insertion_point(module_scope)
