// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: frame.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// frames are used at all levels
// flatten all message types into this enum
type MessageType int32

const (
	MessageType_TransferPack               MessageType = 0
	MessageType_TransferAck                MessageType = 1
	MessageType_TransferContract           MessageType = 2
	MessageType_TransferProvide            MessageType = 3
	MessageType_TransferAuth               MessageType = 4
	MessageType_TransferCreateStream       MessageType = 5
	MessageType_TransferCreateStreamResult MessageType = 6
	// REMOVED
	MessageType_TransferCloseStream          MessageType = 7
	MessageType_TransferStreamOpen           MessageType = 8
	MessageType_TransferStreamClose          MessageType = 9
	MessageType_TransferCreateContract       MessageType = 10
	MessageType_TransferCreateContractResult MessageType = 11
	MessageType_TransferCloseContract        MessageType = 12
	MessageType_TransferPeerAudit            MessageType = 13
	MessageType_TestSimpleMessage            MessageType = 14
	MessageType_IpIpPacketToProvider         MessageType = 15
	MessageType_IpIpPacketFromProvider       MessageType = 16
	MessageType_IpIpPing                     MessageType = 17
	MessageType_TransferControlPing          MessageType = 18
	MessageType_TransferProvidePing          MessageType = 19
	MessageType_TransferExchangeSignals      MessageType = 20
	MessageType_TransferExchangeSignal       MessageType = 21
	MessageType_TransferStreamReset          MessageType = 22
	// out-of-band control for the per-peer TLS encryption session.
	// `Frame.message_bytes` is a marshaled `EncryptedControl`. Carried inside
	// a regular `Pack`/`Ack` flow, so it is delivered reliably and in order
	// by the existing sequence machinery; the destination `ReceiveSequence`
	// intercepts these frames and routes them into the encryption session
	// instead of the application receive callback.
	MessageType_TransferEncryptedControl MessageType = 23
	// control message that publishes this client's public TLS certificate
	// chain to the platform. `Frame.message_bytes` is a marshaled
	// `EncryptedKey`. Sent once per client on startup (and again when the
	// cert rotates). The platform stores the cert per `client_id` and
	// attaches it to every contract whose destination is this client.
	MessageType_TransferEncryptedKey MessageType = 24
	// control message that publishes this client's long-lived public
	// identity key (Ed25519) to the platform. `Frame.message_bytes` is
	// a marshaled `ClientKey`. The platform stores the public key per
	// `client_id` and serves it via an unauthenticated lookup API, so
	// remote peers can fetch the binding independently of the contract
	// pipeline that the platform itself authors. The corresponding
	// private key is held only by the client process.
	MessageType_TransferClientKey MessageType = 25
	// control message that marks the start of a complete network peers
	// list for the receiving client. `Frame.message_bytes` is a marshaled
	// `NetworkPeersReset`. The receiver clears its peer state; the
	// complete list follows as `TransferNetworkPeersUpdate` messages.
	MessageType_TransferNetworkPeersReset MessageType = 26
	// control message that upserts network peers (and disconnect markers)
	// into the receiving client's peer state. `Frame.message_bytes` is a
	// marshaled `NetworkPeersUpdate`.
	MessageType_TransferNetworkPeersUpdate MessageType = 27
	// control message that asks the client to migrate its platform transport
	// (make-before-break) because the resident is draining.
	// `Frame.message_bytes` is a marshaled `ResidentMigrate`.
	// Older clients ignore the unknown message type and fall back to the
	// drain eviction plus excuse path (CONNECTDRAIN2.md).
	MessageType_TransferResidentMigrate MessageType = 28
	// Provider build/policy identity and per-source security block counters.
	// Older clients ignore this data-path message.
	MessageType_IpIpProviderDiagnostics MessageType = 29
	// A message of a subprotocol registered on the receiving client
	// (SUBPROTOCOL.md). `Frame.message_bytes` is a marshaled `SubprotocolMessage`
	// whose own `message_bytes` are decoded in place by the subprotocol's
	// codec. Never sent to the control id; older clients ignore the unknown
	// message type.
	MessageType_Subprotocol MessageType = 30
	// Asks a peer which subprotocols it can receive. `Frame.message_bytes` is
	// a marshaled `SubprotocolsQuery`; the peer answers with
	// `TransferSubprotocolsQueryResult`. Intercepted by the receiving client,
	// never delivered to application callbacks.
	MessageType_TransferSubprotocolsQuery MessageType = 31
	// The answer to `TransferSubprotocolsQuery`. `Frame.message_bytes` is a
	// marshaled `SubprotocolsQueryResult`.
	MessageType_TransferSubprotocolsQueryResult MessageType = 32
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "TransferPack",
		1:  "TransferAck",
		2:  "TransferContract",
		3:  "TransferProvide",
		4:  "TransferAuth",
		5:  "TransferCreateStream",
		6:  "TransferCreateStreamResult",
		7:  "TransferCloseStream",
		8:  "TransferStreamOpen",
		9:  "TransferStreamClose",
		10: "TransferCreateContract",
		11: "TransferCreateContractResult",
		12: "TransferCloseContract",
		13: "TransferPeerAudit",
		14: "TestSimpleMessage",
		15: "IpIpPacketToProvider",
		16: "IpIpPacketFromProvider",
		17: "IpIpPing",
		18: "TransferControlPing",
		19: "TransferProvidePing",
		20: "TransferExchangeSignals",
		21: "TransferExchangeSignal",
		22: "TransferStreamReset",
		23: "TransferEncryptedControl",
		24: "TransferEncryptedKey",
		25: "TransferClientKey",
		26: "TransferNetworkPeersReset",
		27: "TransferNetworkPeersUpdate",
		28: "TransferResidentMigrate",
		29: "IpIpProviderDiagnostics",
		30: "Subprotocol",
		31: "TransferSubprotocolsQuery",
		32: "TransferSubprotocolsQueryResult",
	}
	MessageType_value = map[string]int32{
		"TransferPack":                    0,
		"TransferAck":                     1,
		"TransferContract":                2,
		"TransferProvide":                 3,
		"TransferAuth":                    4,
		"TransferCreateStream":            5,
		"TransferCreateStreamResult":      6,
		"TransferCloseStream":             7,
		"TransferStreamOpen":              8,
		"TransferStreamClose":             9,
		"TransferCreateContract":          10,
		"TransferCreateContractResult":    11,
		"TransferCloseContract":           12,
		"TransferPeerAudit":               13,
		"TestSimpleMessage":               14,
		"IpIpPacketToProvider":            15,
		"IpIpPacketFromProvider":          16,
		"IpIpPing":                        17,
		"TransferControlPing":             18,
		"TransferProvidePing":             19,
		"TransferExchangeSignals":         20,
		"TransferExchangeSignal":          21,
		"TransferStreamReset":             22,
		"TransferEncryptedControl":        23,
		"TransferEncryptedKey":            24,
		"TransferClientKey":               25,
		"TransferNetworkPeersReset":       26,
		"TransferNetworkPeersUpdate":      27,
		"TransferResidentMigrate":         28,
		"IpIpProviderDiagnostics":         29,
		"Subprotocol":                     30,
		"TransferSubprotocolsQuery":       31,
		"TransferSubprotocolsQueryResult": 32,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_frame_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_frame_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MessageType  MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=bringyour.MessageType" json:"message_type,omitempty"`
	MessageBytes []byte                 `protobuf:"bytes,2,opt,name=message_bytes,json=messageBytes,proto3" json:"message_bytes,omitempty"`
	// true when the message_bytes is the message
	// this is used for messages that are already packed e.g. network packets
	Raw           bool `protobuf:"varint,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TransferPack
}

func (x *Frame) GetMessageBytes() []byte {
	if x != nil {
		return x.MessageBytes
	}
	return nil
}

func (x *Frame) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

var File_frame_proto protoreflect.FileDescriptor

const file_frame_proto_rawDesc = "" +
	"\n" +
	"\vframe.proto\x12\tbringyour\"y\n" +
	"\x05Frame\x129\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x16.bringyour.MessageTypeR\vmessageType\x12#\n" +
	"\rmessage_bytes\x18\x02 \x01(\fR\fmessageBytes\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\bR\x03raw*\xdd\x06\n" +
	"\vMessageType\x12\x10\n" +
	"\fTransferPack\x10\x00\x12\x0f\n" +
	"\vTransferAck\x10\x01\x12\x14\n" +
	"\x10TransferContract\x10\x02\x12\x13\n" +
	"\x0fTransferProvide\x10\x03\x12\x10\n" +
	"\fTransferAuth\x10\x04\x12\x18\n" +
	"\x14TransferCreateStream\x10\x05\x12\x1e\n" +
	"\x1aTransferCreateStreamResult\x10\x06\x12\x17\n" +
	"\x13TransferCloseStream\x10\a\x12\x16\n" +
	"\x12TransferStreamOpen\x10\b\x12\x17\n" +
	"\x13TransferStreamClose\x10\t\x12\x1a\n" +
	"\x16TransferCreateContract\x10\n" +
	"\x12 \n" +
	"\x1cTransferCreateContractResult\x10\v\x12\x19\n" +
	"\x15TransferCloseContract\x10\f\x12\x15\n" +
	"\x11TransferPeerAudit\x10\r\x12\x15\n" +
	"\x11TestSimpleMessage\x10\x0e\x12\x18\n" +
	"\x14IpIpPacketToProvider\x10\x0f\x12\x1a\n" +
	"\x16IpIpPacketFromProvider\x10\x10\x12\f\n" +
	"\bIpIpPing\x10\x11\x12\x17\n" +
	"\x13TransferControlPing\x10\x12\x12\x17\n" +
	"\x13TransferProvidePing\x10\x13\x12\x1b\n" +
	"\x17TransferExchangeSignals\x10\x14\x12\x1a\n" +
	"\x16TransferExchangeSignal\x10\x15\x12\x17\n" +
	"\x13TransferStreamReset\x10\x16\x12\x1c\n" +
	"\x18TransferEncryptedControl\x10\x17\x12\x18\n" +
	"\x14TransferEncryptedKey\x10\x18\x12\x15\n" +
	"\x11TransferClientKey\x10\x19\x12\x1d\n" +
	"\x19TransferNetworkPeersReset\x10\x1a\x12\x1e\n" +
	"\x1aTransferNetworkPeersUpdate\x10\x1b\x12\x1b\n" +
	"\x17TransferResidentMigrate\x10\x1c\x12\x1b\n" +
	"\x17IpIpProviderDiagnostics\x10\x1d\x12\x0f\n" +
	"\vSubprotocol\x10\x1e\x12\x1d\n" +
	"\x19TransferSubprotocolsQuery\x10\x1f\x12#\n" +
	"\x1fTransferSubprotocolsQueryResult\x10 B'Z%github.com/urnetwork/connect/protocolb\x06proto3"

var (
	file_frame_proto_rawDescOnce sync.Once
	file_frame_proto_rawDescData []byte
)

func file_frame_proto_rawDescGZIP() []byte {
	file_frame_proto_rawDescOnce.Do(func() {
		file_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)))
	})
	return file_frame_proto_rawDescData
}

var file_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frame_proto_goTypes = []any{
	(MessageType)(0), // 0: bringyour.MessageType
	(*Frame)(nil),    // 1: bringyour.Frame
}
var file_frame_proto_depIdxs = []int32{
	0, // 0: bringyour.Frame.message_type:type_name -> bringyour.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frame_proto_init() }
func file_frame_proto_init() {
	if File_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frame_proto_goTypes,
		DependencyIndexes: file_frame_proto_depIdxs,
		EnumInfos:         file_frame_proto_enumTypes,
		MessageInfos:      file_frame_proto_msgTypes,
	}.Build()
	File_frame_proto = out.File
	file_frame_proto_goTypes = nil
	file_frame_proto_depIdxs = nil
}
