// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: subprotocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message of a subprotocol registered on the receiving client
// (SUBPROTOCOL.md). The frame is `MessageType.Subprotocol` (an enum value
// shares the package scope, hence the `Message` suffix here); the client
// hand-rolls this encoding so the codec of the subprotocol writes and reads
// `message_bytes` in place, with no second copy.
type SubprotocolMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1..65535; ids below 1024 are reserved for the network
	SubprotocolId uint32 `protobuf:"varint,1,opt,name=subprotocol_id,json=subprotocolId,proto3" json:"subprotocol_id,omitempty"`
	// the subprotocol's own encoding, decoded in place by its codec
	MessageBytes  []byte `protobuf:"bytes,2,opt,name=message_bytes,json=messageBytes,proto3" json:"message_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubprotocolMessage) Reset() {
	*x = SubprotocolMessage{}
	mi := &file_subprotocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubprotocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubprotocolMessage) ProtoMessage() {}

func (x *SubprotocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_subprotocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubprotocolMessage.ProtoReflect.Descriptor instead.
func (*SubprotocolMessage) Descriptor() ([]byte, []int) {
	return file_subprotocol_proto_rawDescGZIP(), []int{0}
}

func (x *SubprotocolMessage) GetSubprotocolId() uint32 {
	if x != nil {
		return x.SubprotocolId
	}
	return 0
}

func (x *SubprotocolMessage) GetMessageBytes() []byte {
	if x != nil {
		return x.MessageBytes
	}
	return nil
}

// Asks a peer which subprotocols it can receive (registered codecs and raw
// listeners). Answered with `SubprotocolsQueryResult`; an older peer ignores
// the query, so no result means "unknown", not "none".
type SubprotocolsQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ulid, threaded back on the result
	QueryId       []byte `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubprotocolsQuery) Reset() {
	*x = SubprotocolsQuery{}
	mi := &file_subprotocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubprotocolsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubprotocolsQuery) ProtoMessage() {}

func (x *SubprotocolsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_subprotocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubprotocolsQuery.ProtoReflect.Descriptor instead.
func (*SubprotocolsQuery) Descriptor() ([]byte, []int) {
	return file_subprotocol_proto_rawDescGZIP(), []int{1}
}

func (x *SubprotocolsQuery) GetQueryId() []byte {
	if x != nil {
		return x.QueryId
	}
	return nil
}

type SubprotocolsQueryResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	QueryId []byte                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// every id the sender can receive, sorted and deduplicated
	SubprotocolIds []uint32 `protobuf:"varint,2,rep,packed,name=subprotocol_ids,json=subprotocolIds,proto3" json:"subprotocol_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubprotocolsQueryResult) Reset() {
	*x = SubprotocolsQueryResult{}
	mi := &file_subprotocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubprotocolsQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubprotocolsQueryResult) ProtoMessage() {}

func (x *SubprotocolsQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_subprotocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubprotocolsQueryResult.ProtoReflect.Descriptor instead.
func (*SubprotocolsQueryResult) Descriptor() ([]byte, []int) {
	return file_subprotocol_proto_rawDescGZIP(), []int{2}
}

func (x *SubprotocolsQueryResult) GetQueryId() []byte {
	if x != nil {
		return x.QueryId
	}
	return nil
}

func (x *SubprotocolsQueryResult) GetSubprotocolIds() []uint32 {
	if x != nil {
		return x.SubprotocolIds
	}
	return nil
}

var File_subprotocol_proto protoreflect.FileDescriptor

const file_subprotocol_proto_rawDesc = "" +
	"\n" +
	"\x11subprotocol.proto\x12\tbringyour\"`\n" +
	"\x12SubprotocolMessage\x12%\n" +
	"\x0esubprotocol_id\x18\x01 \x01(\rR\rsubprotocolId\x12#\n" +
	"\rmessage_bytes\x18\x02 \x01(\fR\fmessageBytes\".\n" +
	"\x11SubprotocolsQuery\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\fR\aqueryId\"]\n" +
	"\x17SubprotocolsQueryResult\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\fR\aqueryId\x12'\n" +
	"\x0fsubprotocol_ids\x18\x02 \x03(\rR\x0esubprotocolIdsB'Z%github.com/urnetwork/connect/protocolb\x06proto3"

var (
	file_subprotocol_proto_rawDescOnce sync.Once
	file_subprotocol_proto_rawDescData []byte
)

func file_subprotocol_proto_rawDescGZIP() []byte {
	file_subprotocol_proto_rawDescOnce.Do(func() {
		file_subprotocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subprotocol_proto_rawDesc), len(file_subprotocol_proto_rawDesc)))
	})
	return file_subprotocol_proto_rawDescData
}

var file_subprotocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_subprotocol_proto_goTypes = []any{
	(*SubprotocolMessage)(nil),      // 0: bringyour.SubprotocolMessage
	(*SubprotocolsQuery)(nil),       // 1: bringyour.SubprotocolsQuery
	(*SubprotocolsQueryResult)(nil), // 2: bringyour.SubprotocolsQueryResult
}
var file_subprotocol_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subprotocol_proto_init() }
func file_subprotocol_proto_init() {
	if File_subprotocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subprotocol_proto_rawDesc), len(file_subprotocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subprotocol_proto_goTypes,
		DependencyIndexes: file_subprotocol_proto_depIdxs,
		MessageInfos:      file_subprotocol_proto_msgTypes,
	}.Build()
	File_subprotocol_proto = out.File
	file_subprotocol_proto_goTypes = nil
	file_subprotocol_proto_depIdxs = nil
}
